name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"

jobs:
  test:
    timeout-minutes: 10

    runs-on: macos-12

    steps:
      - name: Install
        run: brew install --cask ci7lus/miraktest/miraktest
      - name: Uninstall
        run: brew uninstall miraktest
